version: "3"

services:
  jenkins-slave:
    image: inogo/docker-ssh-slave:1.24.0
    command: setup-sshd "<REPLACE_WITH_PUB_KEY>"
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
